### PR TITLE
Request: Advanced cosine function guidance added to LyingSigmaSampler

### PR DESCRIPTION
**Pull request by tatookan**
Thanks to the great open source community for sharing what we do.

I've added an advanced cosine function to LyingSigmaSampler, which allows for smoother control and more precise parameterization.
Also I have updated some of the README.

### CODE REVIEW

**Comment by tatookan** [comment]
Any questions, please contact me, thank you.
Here's my email: dianyuanan@vip.qq.com

**Comment by Jonseed** [comment]
@blepping what do you think about this pull request?

**Comment by blepping** [comment]
@Jonseed 

the main node actually already has that cos smoothing: https://github.com/Jonseed/ComfyUI-Detail-Daemon/blob/01e3979272806ef90985955b4bd9397f525062b7/detail_daemon_node.py#L47

looking at that, it seems like it would be possible to get the same result by setting parameters to the normal detail daemon node. i guess the question would be: do you want to keep the lying sigma sampler node simple or do you want to add features from the main node to it?

aside from that, probably isn't a good idea to have example links in your documentation pointing to a different repo you don't control so you'd probably want to request some changes (or you can make a remote branch and edit the pull to point at it, merge it into that and change stuff yourself before you merge it into `main`)

not sure about the noise mask stuff, it probably means my original implementation doesn't handle the case where there's a noise mask function correctly. i _think_ the only thing that actually uses it right now is the `DifferentialDiffusion` node.

**Comment by Jonseed** [comment]
@blepping if it already has cos smoothing, then I don't know what the purpose of this pull request is. I think I would prefer keeping your Lying Sigma sampler simple, and the more complex features in the Detail Daemon node. I agree having example links to a different repo aren't good either. Thanks for your help.

**Comment by blepping** [comment]
@tatookan thanks for your contribution! right now it seems like it's possible to use cos smoothing in the main Detailer Daemon node and it's probably better to keep the Lying Sigma Sampler node simple. that way people can choose between an advanced node with more features or something pretty basic and simple.

your fix to the denoise mask function handling looks useful. you might consider submitting a separate pull that fixes that for the two sampler nodes - right now i don't think i handled that part correctly.

**Comment by tatookan** [comment]
@blepping @Jonseed  my opinion, the LyingSigmaSampler is a very useful node, as many users find it difficult to understand complex parameters. For these users, they might only need a simple, lightweight, and easy-to-use node. However, I have observed that LyingSigmaSampler does not control the noise mask smoothly enough, or in other words, it cannot control it more precisely. LyingSigmaSampler has a great advantage, of course, other nodes are also great. They can be applied to most models, including SD3.5, and they work well, which is a challenge for users because they have to deal with different noise masks. Therefore, I have added smoothing processing to LyingSigmaSampler in the hope of helping more people.

Finally, thank you for your replies and contributions, which have been very helpful to me!

**Comment by tatookan** [comment]
@blepping  Thanks for the offer, I'll do it right

**Pull request closed without merging**
